# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/aidanwalsh/SatelliteOrbitalSimulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/aidanwalsh/SatelliteOrbitalSimulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aidanwalsh/SatelliteOrbitalSimulator/CMakeFiles /Users/aidanwalsh/SatelliteOrbitalSimulator//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/aidanwalsh/SatelliteOrbitalSimulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SatelliteOrbitalSimulator

# Build rule for target.
SatelliteOrbitalSimulator: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SatelliteOrbitalSimulator
.PHONY : SatelliteOrbitalSimulator

# fast build rule for target.
SatelliteOrbitalSimulator/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/build
.PHONY : SatelliteOrbitalSimulator/fast

HttpFetcher.o: HttpFetcher.cpp.o
.PHONY : HttpFetcher.o

# target to build an object file
HttpFetcher.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/HttpFetcher.cpp.o
.PHONY : HttpFetcher.cpp.o

HttpFetcher.i: HttpFetcher.cpp.i
.PHONY : HttpFetcher.i

# target to preprocess a source file
HttpFetcher.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/HttpFetcher.cpp.i
.PHONY : HttpFetcher.cpp.i

HttpFetcher.s: HttpFetcher.cpp.s
.PHONY : HttpFetcher.s

# target to generate assembly for a file
HttpFetcher.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/HttpFetcher.cpp.s
.PHONY : HttpFetcher.cpp.s

SGP4Propagator.o: SGP4Propagator.cpp.o
.PHONY : SGP4Propagator.o

# target to build an object file
SGP4Propagator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/SGP4Propagator.cpp.o
.PHONY : SGP4Propagator.cpp.o

SGP4Propagator.i: SGP4Propagator.cpp.i
.PHONY : SGP4Propagator.i

# target to preprocess a source file
SGP4Propagator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/SGP4Propagator.cpp.i
.PHONY : SGP4Propagator.cpp.i

SGP4Propagator.s: SGP4Propagator.cpp.s
.PHONY : SGP4Propagator.s

# target to generate assembly for a file
SGP4Propagator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/SGP4Propagator.cpp.s
.PHONY : SGP4Propagator.cpp.s

TLEParser.o: TLEParser.cpp.o
.PHONY : TLEParser.o

# target to build an object file
TLEParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/TLEParser.cpp.o
.PHONY : TLEParser.cpp.o

TLEParser.i: TLEParser.cpp.i
.PHONY : TLEParser.i

# target to preprocess a source file
TLEParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/TLEParser.cpp.i
.PHONY : TLEParser.cpp.i

TLEParser.s: TLEParser.cpp.s
.PHONY : TLEParser.s

# target to generate assembly for a file
TLEParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/TLEParser.cpp.s
.PHONY : TLEParser.cpp.s

libs/SGP4/libsgp4/CoordGeodetic.o: libs/SGP4/libsgp4/CoordGeodetic.cc.o
.PHONY : libs/SGP4/libsgp4/CoordGeodetic.o

# target to build an object file
libs/SGP4/libsgp4/CoordGeodetic.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/CoordGeodetic.cc.o
.PHONY : libs/SGP4/libsgp4/CoordGeodetic.cc.o

libs/SGP4/libsgp4/CoordGeodetic.i: libs/SGP4/libsgp4/CoordGeodetic.cc.i
.PHONY : libs/SGP4/libsgp4/CoordGeodetic.i

# target to preprocess a source file
libs/SGP4/libsgp4/CoordGeodetic.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/CoordGeodetic.cc.i
.PHONY : libs/SGP4/libsgp4/CoordGeodetic.cc.i

libs/SGP4/libsgp4/CoordGeodetic.s: libs/SGP4/libsgp4/CoordGeodetic.cc.s
.PHONY : libs/SGP4/libsgp4/CoordGeodetic.s

# target to generate assembly for a file
libs/SGP4/libsgp4/CoordGeodetic.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/CoordGeodetic.cc.s
.PHONY : libs/SGP4/libsgp4/CoordGeodetic.cc.s

libs/SGP4/libsgp4/CoordTopocentric.o: libs/SGP4/libsgp4/CoordTopocentric.cc.o
.PHONY : libs/SGP4/libsgp4/CoordTopocentric.o

# target to build an object file
libs/SGP4/libsgp4/CoordTopocentric.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/CoordTopocentric.cc.o
.PHONY : libs/SGP4/libsgp4/CoordTopocentric.cc.o

libs/SGP4/libsgp4/CoordTopocentric.i: libs/SGP4/libsgp4/CoordTopocentric.cc.i
.PHONY : libs/SGP4/libsgp4/CoordTopocentric.i

# target to preprocess a source file
libs/SGP4/libsgp4/CoordTopocentric.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/CoordTopocentric.cc.i
.PHONY : libs/SGP4/libsgp4/CoordTopocentric.cc.i

libs/SGP4/libsgp4/CoordTopocentric.s: libs/SGP4/libsgp4/CoordTopocentric.cc.s
.PHONY : libs/SGP4/libsgp4/CoordTopocentric.s

# target to generate assembly for a file
libs/SGP4/libsgp4/CoordTopocentric.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/CoordTopocentric.cc.s
.PHONY : libs/SGP4/libsgp4/CoordTopocentric.cc.s

libs/SGP4/libsgp4/DateTime.o: libs/SGP4/libsgp4/DateTime.cc.o
.PHONY : libs/SGP4/libsgp4/DateTime.o

# target to build an object file
libs/SGP4/libsgp4/DateTime.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/DateTime.cc.o
.PHONY : libs/SGP4/libsgp4/DateTime.cc.o

libs/SGP4/libsgp4/DateTime.i: libs/SGP4/libsgp4/DateTime.cc.i
.PHONY : libs/SGP4/libsgp4/DateTime.i

# target to preprocess a source file
libs/SGP4/libsgp4/DateTime.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/DateTime.cc.i
.PHONY : libs/SGP4/libsgp4/DateTime.cc.i

libs/SGP4/libsgp4/DateTime.s: libs/SGP4/libsgp4/DateTime.cc.s
.PHONY : libs/SGP4/libsgp4/DateTime.s

# target to generate assembly for a file
libs/SGP4/libsgp4/DateTime.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/DateTime.cc.s
.PHONY : libs/SGP4/libsgp4/DateTime.cc.s

libs/SGP4/libsgp4/DecayedException.o: libs/SGP4/libsgp4/DecayedException.cc.o
.PHONY : libs/SGP4/libsgp4/DecayedException.o

# target to build an object file
libs/SGP4/libsgp4/DecayedException.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/DecayedException.cc.o
.PHONY : libs/SGP4/libsgp4/DecayedException.cc.o

libs/SGP4/libsgp4/DecayedException.i: libs/SGP4/libsgp4/DecayedException.cc.i
.PHONY : libs/SGP4/libsgp4/DecayedException.i

# target to preprocess a source file
libs/SGP4/libsgp4/DecayedException.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/DecayedException.cc.i
.PHONY : libs/SGP4/libsgp4/DecayedException.cc.i

libs/SGP4/libsgp4/DecayedException.s: libs/SGP4/libsgp4/DecayedException.cc.s
.PHONY : libs/SGP4/libsgp4/DecayedException.s

# target to generate assembly for a file
libs/SGP4/libsgp4/DecayedException.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/DecayedException.cc.s
.PHONY : libs/SGP4/libsgp4/DecayedException.cc.s

libs/SGP4/libsgp4/Eci.o: libs/SGP4/libsgp4/Eci.cc.o
.PHONY : libs/SGP4/libsgp4/Eci.o

# target to build an object file
libs/SGP4/libsgp4/Eci.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Eci.cc.o
.PHONY : libs/SGP4/libsgp4/Eci.cc.o

libs/SGP4/libsgp4/Eci.i: libs/SGP4/libsgp4/Eci.cc.i
.PHONY : libs/SGP4/libsgp4/Eci.i

# target to preprocess a source file
libs/SGP4/libsgp4/Eci.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Eci.cc.i
.PHONY : libs/SGP4/libsgp4/Eci.cc.i

libs/SGP4/libsgp4/Eci.s: libs/SGP4/libsgp4/Eci.cc.s
.PHONY : libs/SGP4/libsgp4/Eci.s

# target to generate assembly for a file
libs/SGP4/libsgp4/Eci.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Eci.cc.s
.PHONY : libs/SGP4/libsgp4/Eci.cc.s

libs/SGP4/libsgp4/Globals.o: libs/SGP4/libsgp4/Globals.cc.o
.PHONY : libs/SGP4/libsgp4/Globals.o

# target to build an object file
libs/SGP4/libsgp4/Globals.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Globals.cc.o
.PHONY : libs/SGP4/libsgp4/Globals.cc.o

libs/SGP4/libsgp4/Globals.i: libs/SGP4/libsgp4/Globals.cc.i
.PHONY : libs/SGP4/libsgp4/Globals.i

# target to preprocess a source file
libs/SGP4/libsgp4/Globals.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Globals.cc.i
.PHONY : libs/SGP4/libsgp4/Globals.cc.i

libs/SGP4/libsgp4/Globals.s: libs/SGP4/libsgp4/Globals.cc.s
.PHONY : libs/SGP4/libsgp4/Globals.s

# target to generate assembly for a file
libs/SGP4/libsgp4/Globals.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Globals.cc.s
.PHONY : libs/SGP4/libsgp4/Globals.cc.s

libs/SGP4/libsgp4/Observer.o: libs/SGP4/libsgp4/Observer.cc.o
.PHONY : libs/SGP4/libsgp4/Observer.o

# target to build an object file
libs/SGP4/libsgp4/Observer.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Observer.cc.o
.PHONY : libs/SGP4/libsgp4/Observer.cc.o

libs/SGP4/libsgp4/Observer.i: libs/SGP4/libsgp4/Observer.cc.i
.PHONY : libs/SGP4/libsgp4/Observer.i

# target to preprocess a source file
libs/SGP4/libsgp4/Observer.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Observer.cc.i
.PHONY : libs/SGP4/libsgp4/Observer.cc.i

libs/SGP4/libsgp4/Observer.s: libs/SGP4/libsgp4/Observer.cc.s
.PHONY : libs/SGP4/libsgp4/Observer.s

# target to generate assembly for a file
libs/SGP4/libsgp4/Observer.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Observer.cc.s
.PHONY : libs/SGP4/libsgp4/Observer.cc.s

libs/SGP4/libsgp4/OrbitalElements.o: libs/SGP4/libsgp4/OrbitalElements.cc.o
.PHONY : libs/SGP4/libsgp4/OrbitalElements.o

# target to build an object file
libs/SGP4/libsgp4/OrbitalElements.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/OrbitalElements.cc.o
.PHONY : libs/SGP4/libsgp4/OrbitalElements.cc.o

libs/SGP4/libsgp4/OrbitalElements.i: libs/SGP4/libsgp4/OrbitalElements.cc.i
.PHONY : libs/SGP4/libsgp4/OrbitalElements.i

# target to preprocess a source file
libs/SGP4/libsgp4/OrbitalElements.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/OrbitalElements.cc.i
.PHONY : libs/SGP4/libsgp4/OrbitalElements.cc.i

libs/SGP4/libsgp4/OrbitalElements.s: libs/SGP4/libsgp4/OrbitalElements.cc.s
.PHONY : libs/SGP4/libsgp4/OrbitalElements.s

# target to generate assembly for a file
libs/SGP4/libsgp4/OrbitalElements.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/OrbitalElements.cc.s
.PHONY : libs/SGP4/libsgp4/OrbitalElements.cc.s

libs/SGP4/libsgp4/SGP4.o: libs/SGP4/libsgp4/SGP4.cc.o
.PHONY : libs/SGP4/libsgp4/SGP4.o

# target to build an object file
libs/SGP4/libsgp4/SGP4.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/SGP4.cc.o
.PHONY : libs/SGP4/libsgp4/SGP4.cc.o

libs/SGP4/libsgp4/SGP4.i: libs/SGP4/libsgp4/SGP4.cc.i
.PHONY : libs/SGP4/libsgp4/SGP4.i

# target to preprocess a source file
libs/SGP4/libsgp4/SGP4.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/SGP4.cc.i
.PHONY : libs/SGP4/libsgp4/SGP4.cc.i

libs/SGP4/libsgp4/SGP4.s: libs/SGP4/libsgp4/SGP4.cc.s
.PHONY : libs/SGP4/libsgp4/SGP4.s

# target to generate assembly for a file
libs/SGP4/libsgp4/SGP4.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/SGP4.cc.s
.PHONY : libs/SGP4/libsgp4/SGP4.cc.s

libs/SGP4/libsgp4/SatelliteException.o: libs/SGP4/libsgp4/SatelliteException.cc.o
.PHONY : libs/SGP4/libsgp4/SatelliteException.o

# target to build an object file
libs/SGP4/libsgp4/SatelliteException.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/SatelliteException.cc.o
.PHONY : libs/SGP4/libsgp4/SatelliteException.cc.o

libs/SGP4/libsgp4/SatelliteException.i: libs/SGP4/libsgp4/SatelliteException.cc.i
.PHONY : libs/SGP4/libsgp4/SatelliteException.i

# target to preprocess a source file
libs/SGP4/libsgp4/SatelliteException.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/SatelliteException.cc.i
.PHONY : libs/SGP4/libsgp4/SatelliteException.cc.i

libs/SGP4/libsgp4/SatelliteException.s: libs/SGP4/libsgp4/SatelliteException.cc.s
.PHONY : libs/SGP4/libsgp4/SatelliteException.s

# target to generate assembly for a file
libs/SGP4/libsgp4/SatelliteException.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/SatelliteException.cc.s
.PHONY : libs/SGP4/libsgp4/SatelliteException.cc.s

libs/SGP4/libsgp4/SolarPosition.o: libs/SGP4/libsgp4/SolarPosition.cc.o
.PHONY : libs/SGP4/libsgp4/SolarPosition.o

# target to build an object file
libs/SGP4/libsgp4/SolarPosition.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/SolarPosition.cc.o
.PHONY : libs/SGP4/libsgp4/SolarPosition.cc.o

libs/SGP4/libsgp4/SolarPosition.i: libs/SGP4/libsgp4/SolarPosition.cc.i
.PHONY : libs/SGP4/libsgp4/SolarPosition.i

# target to preprocess a source file
libs/SGP4/libsgp4/SolarPosition.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/SolarPosition.cc.i
.PHONY : libs/SGP4/libsgp4/SolarPosition.cc.i

libs/SGP4/libsgp4/SolarPosition.s: libs/SGP4/libsgp4/SolarPosition.cc.s
.PHONY : libs/SGP4/libsgp4/SolarPosition.s

# target to generate assembly for a file
libs/SGP4/libsgp4/SolarPosition.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/SolarPosition.cc.s
.PHONY : libs/SGP4/libsgp4/SolarPosition.cc.s

libs/SGP4/libsgp4/TimeSpan.o: libs/SGP4/libsgp4/TimeSpan.cc.o
.PHONY : libs/SGP4/libsgp4/TimeSpan.o

# target to build an object file
libs/SGP4/libsgp4/TimeSpan.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/TimeSpan.cc.o
.PHONY : libs/SGP4/libsgp4/TimeSpan.cc.o

libs/SGP4/libsgp4/TimeSpan.i: libs/SGP4/libsgp4/TimeSpan.cc.i
.PHONY : libs/SGP4/libsgp4/TimeSpan.i

# target to preprocess a source file
libs/SGP4/libsgp4/TimeSpan.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/TimeSpan.cc.i
.PHONY : libs/SGP4/libsgp4/TimeSpan.cc.i

libs/SGP4/libsgp4/TimeSpan.s: libs/SGP4/libsgp4/TimeSpan.cc.s
.PHONY : libs/SGP4/libsgp4/TimeSpan.s

# target to generate assembly for a file
libs/SGP4/libsgp4/TimeSpan.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/TimeSpan.cc.s
.PHONY : libs/SGP4/libsgp4/TimeSpan.cc.s

libs/SGP4/libsgp4/Tle.o: libs/SGP4/libsgp4/Tle.cc.o
.PHONY : libs/SGP4/libsgp4/Tle.o

# target to build an object file
libs/SGP4/libsgp4/Tle.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Tle.cc.o
.PHONY : libs/SGP4/libsgp4/Tle.cc.o

libs/SGP4/libsgp4/Tle.i: libs/SGP4/libsgp4/Tle.cc.i
.PHONY : libs/SGP4/libsgp4/Tle.i

# target to preprocess a source file
libs/SGP4/libsgp4/Tle.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Tle.cc.i
.PHONY : libs/SGP4/libsgp4/Tle.cc.i

libs/SGP4/libsgp4/Tle.s: libs/SGP4/libsgp4/Tle.cc.s
.PHONY : libs/SGP4/libsgp4/Tle.s

# target to generate assembly for a file
libs/SGP4/libsgp4/Tle.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Tle.cc.s
.PHONY : libs/SGP4/libsgp4/Tle.cc.s

libs/SGP4/libsgp4/TleException.o: libs/SGP4/libsgp4/TleException.cc.o
.PHONY : libs/SGP4/libsgp4/TleException.o

# target to build an object file
libs/SGP4/libsgp4/TleException.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/TleException.cc.o
.PHONY : libs/SGP4/libsgp4/TleException.cc.o

libs/SGP4/libsgp4/TleException.i: libs/SGP4/libsgp4/TleException.cc.i
.PHONY : libs/SGP4/libsgp4/TleException.i

# target to preprocess a source file
libs/SGP4/libsgp4/TleException.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/TleException.cc.i
.PHONY : libs/SGP4/libsgp4/TleException.cc.i

libs/SGP4/libsgp4/TleException.s: libs/SGP4/libsgp4/TleException.cc.s
.PHONY : libs/SGP4/libsgp4/TleException.s

# target to generate assembly for a file
libs/SGP4/libsgp4/TleException.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/TleException.cc.s
.PHONY : libs/SGP4/libsgp4/TleException.cc.s

libs/SGP4/libsgp4/Util.o: libs/SGP4/libsgp4/Util.cc.o
.PHONY : libs/SGP4/libsgp4/Util.o

# target to build an object file
libs/SGP4/libsgp4/Util.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Util.cc.o
.PHONY : libs/SGP4/libsgp4/Util.cc.o

libs/SGP4/libsgp4/Util.i: libs/SGP4/libsgp4/Util.cc.i
.PHONY : libs/SGP4/libsgp4/Util.i

# target to preprocess a source file
libs/SGP4/libsgp4/Util.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Util.cc.i
.PHONY : libs/SGP4/libsgp4/Util.cc.i

libs/SGP4/libsgp4/Util.s: libs/SGP4/libsgp4/Util.cc.s
.PHONY : libs/SGP4/libsgp4/Util.s

# target to generate assembly for a file
libs/SGP4/libsgp4/Util.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Util.cc.s
.PHONY : libs/SGP4/libsgp4/Util.cc.s

libs/SGP4/libsgp4/Vector.o: libs/SGP4/libsgp4/Vector.cc.o
.PHONY : libs/SGP4/libsgp4/Vector.o

# target to build an object file
libs/SGP4/libsgp4/Vector.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Vector.cc.o
.PHONY : libs/SGP4/libsgp4/Vector.cc.o

libs/SGP4/libsgp4/Vector.i: libs/SGP4/libsgp4/Vector.cc.i
.PHONY : libs/SGP4/libsgp4/Vector.i

# target to preprocess a source file
libs/SGP4/libsgp4/Vector.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Vector.cc.i
.PHONY : libs/SGP4/libsgp4/Vector.cc.i

libs/SGP4/libsgp4/Vector.s: libs/SGP4/libsgp4/Vector.cc.s
.PHONY : libs/SGP4/libsgp4/Vector.s

# target to generate assembly for a file
libs/SGP4/libsgp4/Vector.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/libs/SGP4/libsgp4/Vector.cc.s
.PHONY : libs/SGP4/libsgp4/Vector.cc.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SatelliteOrbitalSimulator.dir/build.make CMakeFiles/SatelliteOrbitalSimulator.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... SatelliteOrbitalSimulator"
	@echo "... HttpFetcher.o"
	@echo "... HttpFetcher.i"
	@echo "... HttpFetcher.s"
	@echo "... SGP4Propagator.o"
	@echo "... SGP4Propagator.i"
	@echo "... SGP4Propagator.s"
	@echo "... TLEParser.o"
	@echo "... TLEParser.i"
	@echo "... TLEParser.s"
	@echo "... libs/SGP4/libsgp4/CoordGeodetic.o"
	@echo "... libs/SGP4/libsgp4/CoordGeodetic.i"
	@echo "... libs/SGP4/libsgp4/CoordGeodetic.s"
	@echo "... libs/SGP4/libsgp4/CoordTopocentric.o"
	@echo "... libs/SGP4/libsgp4/CoordTopocentric.i"
	@echo "... libs/SGP4/libsgp4/CoordTopocentric.s"
	@echo "... libs/SGP4/libsgp4/DateTime.o"
	@echo "... libs/SGP4/libsgp4/DateTime.i"
	@echo "... libs/SGP4/libsgp4/DateTime.s"
	@echo "... libs/SGP4/libsgp4/DecayedException.o"
	@echo "... libs/SGP4/libsgp4/DecayedException.i"
	@echo "... libs/SGP4/libsgp4/DecayedException.s"
	@echo "... libs/SGP4/libsgp4/Eci.o"
	@echo "... libs/SGP4/libsgp4/Eci.i"
	@echo "... libs/SGP4/libsgp4/Eci.s"
	@echo "... libs/SGP4/libsgp4/Globals.o"
	@echo "... libs/SGP4/libsgp4/Globals.i"
	@echo "... libs/SGP4/libsgp4/Globals.s"
	@echo "... libs/SGP4/libsgp4/Observer.o"
	@echo "... libs/SGP4/libsgp4/Observer.i"
	@echo "... libs/SGP4/libsgp4/Observer.s"
	@echo "... libs/SGP4/libsgp4/OrbitalElements.o"
	@echo "... libs/SGP4/libsgp4/OrbitalElements.i"
	@echo "... libs/SGP4/libsgp4/OrbitalElements.s"
	@echo "... libs/SGP4/libsgp4/SGP4.o"
	@echo "... libs/SGP4/libsgp4/SGP4.i"
	@echo "... libs/SGP4/libsgp4/SGP4.s"
	@echo "... libs/SGP4/libsgp4/SatelliteException.o"
	@echo "... libs/SGP4/libsgp4/SatelliteException.i"
	@echo "... libs/SGP4/libsgp4/SatelliteException.s"
	@echo "... libs/SGP4/libsgp4/SolarPosition.o"
	@echo "... libs/SGP4/libsgp4/SolarPosition.i"
	@echo "... libs/SGP4/libsgp4/SolarPosition.s"
	@echo "... libs/SGP4/libsgp4/TimeSpan.o"
	@echo "... libs/SGP4/libsgp4/TimeSpan.i"
	@echo "... libs/SGP4/libsgp4/TimeSpan.s"
	@echo "... libs/SGP4/libsgp4/Tle.o"
	@echo "... libs/SGP4/libsgp4/Tle.i"
	@echo "... libs/SGP4/libsgp4/Tle.s"
	@echo "... libs/SGP4/libsgp4/TleException.o"
	@echo "... libs/SGP4/libsgp4/TleException.i"
	@echo "... libs/SGP4/libsgp4/TleException.s"
	@echo "... libs/SGP4/libsgp4/Util.o"
	@echo "... libs/SGP4/libsgp4/Util.i"
	@echo "... libs/SGP4/libsgp4/Util.s"
	@echo "... libs/SGP4/libsgp4/Vector.o"
	@echo "... libs/SGP4/libsgp4/Vector.i"
	@echo "... libs/SGP4/libsgp4/Vector.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

